import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/layout/sidebar/provider";
import { Sidebar } from "@/components/layout/sidebar/sidebar";
import { ThemeProvider } from "@/components/theme/provider";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <Script src="https://kit.fontawesome.com/40c3b5129c.js" crossOrigin="anonymous" />
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-200 flex min-h-screen`}>
                <ThemeProvider>
                    <SidebarProvider>
                        <Sidebar />
                        <div className="flex-1 flex flex-col bg-base-200 min-h-screen pb-auto">
                            <Header />
                            <div className="grow p-6">
                                {children}
                            </div>
                            <Footer />
                        </div>
                    </SidebarProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
